<?php if ($this->getIsEnabled()): ?>
<script type="text/javascript">
//<![CDATA[
var bongo_html = '<form id="bongo_form" action="<?php echo $this->getCheckoutUrl (); ?>" method="post">'+$('bongo_form_div').innerHTML+'</form>';
$('bongo_form_div').remove();
$('checkout-step-shipping_method').insert({'bottom':bongo_html});
$$('#shipping-method-buttons-container button').first().observe('click', function() {
	$('bongo_form').submit();
});
//]]>
</script>
<?php endif; ?>