<?php if ($this->getIsEnabled ()) : ?>
<div id="bongo_loading_div"></div>
<style type="text/css">
<!--
#bongo_checkout_payment_method_load {
	padding:5px 10px;
	font-weight:bold;
}
-->
</style>
<script type="text/javascript">
//<![CDATA[
var __bongo_hide_checkout_review_int;
var __bongo_fetch_shipping_country_timeout;
var __bongo_country_id = $('shipping:country_id') != undefined && $('shipping:country_id').value != null && $('shipping:same_as_billing').checked != true ? $('shipping:country_id').value : $('billing:country_id').value;

function bongoHideCheckoutReview(direct) {
	if (direct != true && checkout.loadWaiting != undefined && checkout.loadWaiting == true) {
		return false;
	}

	if ($('payment-method-review') != undefined) {
		$('payment-method-review').hide();
	}
	
	var last_total = $$('#checkout-review-table tfoot tr').last();
	
	if (last_total.down('td').innerHTML.search(/total incl/i) != -1) {
		last_total.hide();
	}
}

function bongoUpdateShippingCountry() {
	__bongo_country_id = $('shipping:country_id') != undefined && $('shipping:country_id').value != null && $('shipping:same_as_billing').checked != true ? $('shipping:country_id').value : $('billing:country_id').value;

	bongoUpdateCheckout();
}

function bongoFetchShippingCountry() {
	if ((checkout.loadWaiting != undefined && checkout.loadWaiting == true) || $('firecheckout-spinner') != undefined) {
		__bongo_fetch_shipping_country_timeout = setTimeout(bongoFetchShippingCountry, 500);
		
		return false;
	}

	new Ajax.Request('<?php echo $this->getUrl('bongointernational/ajax/shippingCountry', array('_secure' => true)) ?>', {
		method: 'get',
		onComplete: function(xhr)    {
			__bongo_country_id = xhr.responseText;

			bongoUpdateCheckout();
		}
	});
}

function bongoUpdateCheckout() {
	if (__bongo_allowed_countries.indexOf(__bongo_country_id) !== -1) {
		if ($('bongo_checkout_payment_method_load') != undefined) {
			$('bongo_checkout_payment_method_load').show();
		} else {
			$('checkout-payment-method-load').insert({ before: '<div id="bongo_checkout_payment_method_load"><span>Bongo International</span></div>' });
		}
			
		$('checkout-payment-method-load').hide();

		if ($('checkout-coupon-discount-load') != undefined) {
			$('checkout-coupon-discount-load').hide();
		}

		if ($('checkout-additional') != undefined) {
			$('checkout-additional').hide();
			$$('#checkout-review div.block-title span.num').first().update('4');
		}

		bongoHideCheckoutReview(true);
		
		__bongo_hide_checkout_review_int = setInterval(bongoHideCheckoutReview, 500);
		
		return false;
	} else {
		if ($('bongo_checkout_payment_method_load') != undefined) {
			$('bongo_checkout_payment_method_load').hide();
		}

		$('checkout-payment-method-load').show();

		if ($('checkout-coupon-discount-load') != undefined) {
			$('checkout-coupon-discount-load').show();
		}

		if ($('checkout-additional') != undefined) {
			$('checkout-additional').show();
			$$('div#checkout-review div.block-title span.num').first().update('5');
		}

		if ($('payment-method-review') != undefined) {
			$('payment-method-review').hide();
		}

		var last_total = $$('#checkout-review-table tfoot tr').last();
		
		if (last_total.down('td').innerHTML.search(/total incl/i) != -1) {
			last_total.show();
		}

		clearInterval(__bongo_hide_checkout_review_int);
	}
}

function bongoCheckSaveStatus () {
	if($('firecheckout-spinner') != undefined) {
		setTimeout(bongoCheckSaveStatus, '500');
	} else {
		checkout.setLoadWaiting(true);
        $('review-please-wait').show();
        
        new Ajax.Request('<?php echo $this->getUrl('bongointernational/ajax', array('_secure' => true)) ?>', {
    		method: 'get',
    		onComplete: function(xhr)    {
    			$('bongo_loading_div').update(xhr.responseText);
				$('bongo_form').submit();
    		}
    	});
	}
}

if ($('firecheckout-form') != undefined) {
	$('billing:country_id').observe('change', bongoUpdateShippingCountry);
	$('shipping:country_id').observe('change', bongoUpdateShippingCountry);
	$('shipping:same_as_billing').observe('change', function () {
		__bongo_fetch_shipping_country_timeout = setTimeout(bongoFetchShippingCountry, 500);
	});
	$('billing-address-select').observe('change', function () {
		__bongo_fetch_shipping_country_timeout = setTimeout(bongoFetchShippingCountry, 500);
	});
	$('shipping-address-select').observe('change', function () {
		__bongo_fetch_shipping_country_timeout = setTimeout(bongoFetchShippingCountry, 500);
	});
	
	bongoUpdateCheckout();

	var bongo_already_placing_order = false;
	
	$$('#review-buttons-container button').first().writeAttribute('onclick', null);
	$$('#review-buttons-container button').first().observe('click', function() {
		if (__bongo_allowed_countries.indexOf(__bongo_country_id) !== -1) {
			if (bongo_already_placing_order) {
				return false;
			}
			
			// First validate the form
            var form = new VarienForm('firecheckout-form');

            if(!form.validator.validate())  {
                return false;
            }
			
			bongo_already_placing_order = true;
			
			checkout.update(checkout.urls.billing_address, {
                review: 1
            });
			
			setTimeout(bongoCheckSaveStatus, '500');
			
			return false;
		} else {
			checkout.save();
		}

		return false;
	});
}
//]]>
</script>
<?php endif; ?>