<?php
/**
 * Copyright Titan Motorsports 2017
 * Author Mark Lutz
 * Create Date 03/29/2017
 * 
 * 
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>

<!DOCTYPE html>

<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js"> <!--<![endif]-->

<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col2-left-layout">
            <div class="main">
                <!--?php echo $this->getChildHtml('breadcrumbs') ?-->
                <?php // This left_first block will display above the main content on smaller viewports ?>
                <!--?php if ($_leftContent = $this->getChildHtml('left_first')): ?>
                <div class="col-left sidebar col-left-first"> --><!--?php echo $_leftContent;   ?></div-->
                <!--?php endif; ?-->
                <div class="col-left sidebar"><?php echo $this->getChildHtml('left') ?></div>
                <div class="col-main">
					<?php
						// IF WE ARE ON HOMEPAGE
						$action = Mage::app()->getFrontController()->getAction()->getFullActionName();
					//echo $action ;
					if($action != 'cms_index_index') : 
						// Put your homepage-only code in here.
					?>
<div class="tms_BreadCrumb_Container">
<div class="tms_BreadCrumb_Header"> breadcrumbs Not Working
<?php

echo $this->getChildHtml('breadcrumbs'); 
?>
								<!--?php echo $this->getChildHtml('onlybreadcrumbs') ?-->
							</div>
						</div>
					<?php endif; ?>
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
