<?php if ($this->getIsEnabled ()) : ?>
<script type="text/javascript">
//<![CDATA[
var __bongo_allowed_countries = <?php echo json_encode ( $this->getAllowedCountries () ); ?>

Element.prototype.triggerEvent = function(eventName)
{
    if (document.createEvent)
    {
        var evt = document.createEvent('HTMLEvents');
        evt.initEvent(eventName, true, true);

        return this.dispatchEvent(evt);
    }

    if (this.fireEvent)
        return this.fireEvent('on' + eventName);
}
//]]>
</script>
<?php endif; ?>